/**
 * Curated emoji set for the built-in picker. Deliberately compact (a few
 * hundred of the most-used, not the full ~1900 Unicode set) so the widget
 * stays tiny and dependency-free. Each entry: emoji + search keywords, and
 * `s: true` when it accepts a skin-tone modifier.
 */

export interface EmojiEntry {
  e: string; // the emoji
  k: string; // space-separated search keywords
  s?: boolean; // skin-tone-able
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

/** Skin-tone modifiers (index 0 = default/none). */
export const SKIN_TONES = ["", "\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"];
export const SKIN_SWATCHES = ["✋", "✋🏻", "✋🏼", "✋🏽", "✋🏾", "✋🏿"];

/** Apply a skin tone to a skin-tone-able base emoji (no-op for others). */
export function withSkin(entry: EmojiEntry, tone: number): string {
  if (!entry.s || tone <= 0 || tone >= SKIN_TONES.length) return entry.e;
  return entry.e + SKIN_TONES[tone];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    icon: "😊",
    emojis: [
      { e: "😀", k: "grin happy smile" },
      { e: "😃", k: "smile happy joy" },
      { e: "😄", k: "smile laugh happy" },
      { e: "😁", k: "grin beam" },
      { e: "😆", k: "laugh haha" },
      { e: "😅", k: "sweat laugh relief" },
      { e: "😂", k: "joy laugh cry tears" },
      { e: "🤣", k: "rofl laughing rolling" },
      { e: "😊", k: "blush smile happy" },
      { e: "🙂", k: "slight smile" },
      { e: "😉", k: "wink" },
      { e: "😍", k: "love heart eyes" },
      { e: "🥰", k: "love hearts adore" },
      { e: "😘", k: "kiss love" },
      { e: "😗", k: "kiss" },
      { e: "😜", k: "tongue wink playful" },
      { e: "🤪", k: "zany silly crazy" },
      { e: "🤗", k: "hug" },
      { e: "🤔", k: "thinking hmm" },
      { e: "🤨", k: "raised eyebrow skeptic" },
      { e: "😐", k: "neutral meh" },
      { e: "😶", k: "no mouth silent" },
      { e: "🙄", k: "eye roll" },
      { e: "😏", k: "smirk" },
      { e: "😴", k: "sleep tired zzz" },
      { e: "😌", k: "relieved calm" },
      { e: "😔", k: "sad pensive" },
      { e: "😢", k: "cry sad tear" },
      { e: "😭", k: "sob cry sad" },
      { e: "😤", k: "frustrated steam" },
      { e: "😠", k: "angry mad" },
      { e: "😡", k: "rage angry mad" },
      { e: "🤯", k: "mind blown shock" },
      { e: "😳", k: "flushed embarrassed" },
      { e: "🥵", k: "hot heat sweat" },
      { e: "🥶", k: "cold freezing" },
      { e: "😱", k: "scream shock fear" },
      { e: "😨", k: "fearful scared" },
      { e: "😰", k: "anxious sweat" },
      { e: "🤢", k: "sick nausea" },
      { e: "🤮", k: "vomit sick" },
      { e: "😷", k: "mask sick" },
      { e: "🤒", k: "sick thermometer" },
      { e: "🤕", k: "hurt bandage" },
      { e: "🥳", k: "party celebrate" },
      { e: "😎", k: "cool sunglasses" },
      { e: "🤓", k: "nerd glasses" },
      { e: "🥺", k: "pleading puppy eyes" },
      { e: "😇", k: "angel halo innocent" },
    ],
  },
  {
    id: "gestures",
    label: "People",
    icon: "👋",
    emojis: [
      { e: "👋", k: "wave hello hi bye", s: true },
      { e: "🤚", k: "raised hand back", s: true },
      { e: "✋", k: "hand stop high five", s: true },
      { e: "👌", k: "ok perfect", s: true },
      { e: "🤌", k: "pinched fingers", s: true },
      { e: "✌️", k: "victory peace", s: true },
      { e: "🤞", k: "fingers crossed luck", s: true },
      { e: "🤟", k: "love you", s: true },
      { e: "🤙", k: "call me hang loose", s: true },
      { e: "👈", k: "point left", s: true },
      { e: "👉", k: "point right", s: true },
      { e: "👆", k: "point up", s: true },
      { e: "👇", k: "point down", s: true },
      { e: "👍", k: "thumbs up like yes good", s: true },
      { e: "👎", k: "thumbs down dislike no", s: true },
      { e: "✊", k: "fist", s: true },
      { e: "👊", k: "punch fist bump", s: true },
      { e: "👏", k: "clap applause", s: true },
      { e: "🙌", k: "raised hands celebrate praise", s: true },
      { e: "🙏", k: "pray thanks please", s: true },
      { e: "🤝", k: "handshake deal" },
      { e: "💪", k: "muscle strong flex", s: true },
      { e: "🫶", k: "heart hands love", s: true },
      { e: "👀", k: "eyes look" },
      { e: "🧑", k: "person", s: true },
      { e: "👩", k: "woman", s: true },
      { e: "👨", k: "man", s: true },
      { e: "👶", k: "baby", s: true },
      { e: "👦", k: "boy", s: true },
      { e: "👧", k: "girl", s: true },
      { e: "👨‍👩‍👧‍👦", k: "family" },
      { e: "🧑‍💻", k: "developer coder tech", s: true },
      { e: "💁", k: "info tipping hand", s: true },
      { e: "🙋", k: "raise hand question", s: true },
      { e: "🤦", k: "facepalm", s: true },
      { e: "🤷", k: "shrug dunno", s: true },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icon: "🌿",
    emojis: [
      { e: "🐶", k: "dog puppy" },
      { e: "🐱", k: "cat" },
      { e: "🦊", k: "fox" },
      { e: "🐻", k: "bear" },
      { e: "🐼", k: "panda" },
      { e: "🐨", k: "koala" },
      { e: "🦁", k: "lion" },
      { e: "🐯", k: "tiger" },
      { e: "🐷", k: "pig" },
      { e: "🐵", k: "monkey" },
      { e: "🐔", k: "chicken" },
      { e: "🐧", k: "penguin" },
      { e: "🐦", k: "bird" },
      { e: "🦄", k: "unicorn" },
      { e: "🐝", k: "bee" },
      { e: "🦋", k: "butterfly" },
      { e: "🐢", k: "turtle" },
      { e: "🐬", k: "dolphin" },
      { e: "🐳", k: "whale" },
      { e: "🌵", k: "cactus" },
      { e: "🌲", k: "tree evergreen" },
      { e: "🌴", k: "palm tree" },
      { e: "🌿", k: "herb leaf plant" },
      { e: "🍀", k: "clover luck" },
      { e: "🌸", k: "blossom flower" },
      { e: "🌺", k: "hibiscus flower" },
      { e: "🌻", k: "sunflower" },
      { e: "🌹", k: "rose flower" },
      { e: "🌈", k: "rainbow" },
      { e: "☀️", k: "sun sunny" },
      { e: "⛅", k: "cloud sun" },
      { e: "☁️", k: "cloud" },
      { e: "🌧️", k: "rain" },
      { e: "⚡", k: "lightning bolt" },
      { e: "❄️", k: "snow snowflake cold" },
      { e: "🔥", k: "fire hot lit" },
      { e: "💧", k: "water drop" },
      { e: "🌊", k: "wave ocean sea" },
      { e: "⭐", k: "star" },
      { e: "🌙", k: "moon" },
    ],
  },
  {
    id: "food",
    label: "Food",
    icon: "🍔",
    emojis: [
      { e: "🍎", k: "apple" },
      { e: "🍌", k: "banana" },
      { e: "🍉", k: "watermelon" },
      { e: "🍇", k: "grapes" },
      { e: "🍓", k: "strawberry" },
      { e: "🍒", k: "cherry" },
      { e: "🍑", k: "peach" },
      { e: "🍍", k: "pineapple" },
      { e: "🥑", k: "avocado" },
      { e: "🍅", k: "tomato" },
      { e: "🌽", k: "corn" },
      { e: "🥕", k: "carrot" },
      { e: "🍔", k: "burger hamburger" },
      { e: "🍟", k: "fries chips" },
      { e: "🍕", k: "pizza" },
      { e: "🌭", k: "hot dog" },
      { e: "🥪", k: "sandwich" },
      { e: "🌮", k: "taco" },
      { e: "🍜", k: "noodles ramen" },
      { e: "🍣", k: "sushi" },
      { e: "🍦", k: "ice cream" },
      { e: "🍩", k: "donut" },
      { e: "🍪", k: "cookie" },
      { e: "🎂", k: "cake birthday" },
      { e: "🍰", k: "cake slice" },
      { e: "🍫", k: "chocolate" },
      { e: "🍿", k: "popcorn" },
      { e: "☕", k: "coffee tea" },
      { e: "🍵", k: "tea green" },
      { e: "🍺", k: "beer" },
      { e: "🍷", k: "wine" },
      { e: "🥂", k: "cheers champagne toast" },
      { e: "🍾", k: "champagne celebrate" },
    ],
  },
  {
    id: "activities",
    label: "Activity",
    icon: "⚽",
    emojis: [
      { e: "⚽", k: "soccer football" },
      { e: "🏀", k: "basketball" },
      { e: "🏈", k: "football american" },
      { e: "⚾", k: "baseball" },
      { e: "🎾", k: "tennis" },
      { e: "🏐", k: "volleyball" },
      { e: "🏓", k: "ping pong table tennis" },
      { e: "🏸", k: "badminton" },
      { e: "🥅", k: "goal net" },
      { e: "⛳", k: "golf" },
      { e: "🏆", k: "trophy win" },
      { e: "🥇", k: "gold medal first" },
      { e: "🎯", k: "target dart bullseye" },
      { e: "🎮", k: "game controller" },
      { e: "🎲", k: "dice game" },
      { e: "🎸", k: "guitar music" },
      { e: "🎹", k: "piano keyboard" },
      { e: "🎺", k: "trumpet" },
      { e: "🎻", k: "violin" },
      { e: "🎤", k: "microphone sing" },
      { e: "🎧", k: "headphones music" },
      { e: "🎨", k: "art palette paint" },
      { e: "🎬", k: "movie clapper film" },
      { e: "🎉", k: "party tada celebrate" },
      { e: "🎊", k: "confetti celebrate" },
      { e: "🎁", k: "gift present" },
      { e: "🎈", k: "balloon party" },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      { e: "📱", k: "phone mobile" },
      { e: "💻", k: "laptop computer" },
      { e: "⌨️", k: "keyboard" },
      { e: "🖥️", k: "desktop computer monitor" },
      { e: "🖨️", k: "printer" },
      { e: "📷", k: "camera photo" },
      { e: "🎥", k: "video camera" },
      { e: "📺", k: "tv television" },
      { e: "🔋", k: "battery" },
      { e: "🔌", k: "plug power" },
      { e: "💡", k: "idea light bulb" },
      { e: "🔦", k: "flashlight" },
      { e: "📚", k: "books library" },
      { e: "📖", k: "book read" },
      { e: "📝", k: "memo note write" },
      { e: "✏️", k: "pencil write" },
      { e: "📌", k: "pin" },
      { e: "📎", k: "paperclip attach" },
      { e: "✂️", k: "scissors cut" },
      { e: "🔑", k: "key" },
      { e: "🔒", k: "lock secure private" },
      { e: "🔓", k: "unlock open" },
      { e: "🔔", k: "bell notification" },
      { e: "📢", k: "megaphone announce" },
      { e: "💰", k: "money bag" },
      { e: "💳", k: "credit card payment" },
      { e: "🛒", k: "cart shopping" },
      { e: "📦", k: "package box shipping" },
      { e: "✉️", k: "email envelope mail" },
      { e: "📧", k: "email" },
      { e: "🗓️", k: "calendar date" },
      { e: "⏰", k: "alarm clock time" },
      { e: "⌛", k: "hourglass time" },
      { e: "🔍", k: "search magnify" },
      { e: "🛠️", k: "tools support fix wrench" },
      { e: "⚙️", k: "gear settings" },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      { e: "❤️", k: "heart love red" },
      { e: "🧡", k: "orange heart" },
      { e: "💛", k: "yellow heart" },
      { e: "💚", k: "green heart" },
      { e: "💙", k: "blue heart" },
      { e: "💜", k: "purple heart" },
      { e: "🖤", k: "black heart" },
      { e: "🤍", k: "white heart" },
      { e: "💔", k: "broken heart" },
      { e: "💕", k: "two hearts love" },
      { e: "💯", k: "hundred perfect score" },
      { e: "✅", k: "check done yes tick" },
      { e: "☑️", k: "checkbox checked" },
      { e: "✔️", k: "check mark done" },
      { e: "❌", k: "cross no x wrong" },
      { e: "⭕", k: "circle o correct" },
      { e: "❗", k: "exclamation important" },
      { e: "❓", k: "question" },
      { e: "⚠️", k: "warning caution alert" },
      { e: "🚫", k: "no forbidden ban" },
      { e: "➕", k: "plus add" },
      { e: "➖", k: "minus subtract" },
      { e: "✳️", k: "asterisk" },
      { e: "🔴", k: "red circle" },
      { e: "🟢", k: "green circle" },
      { e: "🔵", k: "blue circle" },
      { e: "⭐", k: "star" },
      { e: "🌟", k: "glowing star sparkle" },
      { e: "✨", k: "sparkles shine" },
      { e: "💥", k: "boom collision" },
      { e: "💫", k: "dizzy star" },
      { e: "🎵", k: "music note" },
      { e: "🇺🇸", k: "flag usa america" },
      { e: "🏳️", k: "white flag" },
      { e: "🏁", k: "checkered flag finish" },
    ],
  },
];

/** Search across all categories by keyword (case-insensitive substring). */
export function searchEmoji(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (q === "") return [];
  const out: EmojiEntry[] = [];
  for (const cat of EMOJI_CATEGORIES) {
    for (const entry of cat.emojis) {
      if (entry.k.includes(q) || entry.e === q) out.push(entry);
      if (out.length >= 60) return out;
    }
  }
  return out;
}
